#!/bin/bash
# Cheat Sheet - Commandes Principales

echo "==============================================="
echo "📚 CV Application - Cheat Sheet"
echo "==============================================="
echo ""

echo "🚀 DÉMARRAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "npm install          → Installer dépendances"
echo "npm run server       → Lancer API (Terminal 1)"
echo "npm start            → Lancer React (Terminal 2)"
echo "npm run dev          → Lancer API + React"
echo ""

echo "📦 BUILD & PRODUCTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "npm run build        → Builder l'app"
echo "npm run start:prod   → Lancer en production"
echo "npm test             → Lancer tests"
echo ""

echo "🐳 DOCKER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "docker build -t cv-app .          → Builder image"
echo "docker run -p 5000:5000 cv-app    → Run container"
echo "docker-compose up -d               → Run avec compose"
echo "docker logs cv-app                 → Voir logs"
echo ""

echo "🌍 URL & ENDPOINTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Frontend      → http://localhost:3000"
echo "Backend       → http://localhost:5000"
echo "Health Check  → http://localhost:5000/api/health"
echo "Resumes API   → http://localhost:5000/api/resumes"
echo ""

echo "🔧 CONFIGURATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cat .env              → Voir variables env"
echo "npm list              → Voir dépendances"
echo "node --version        → Version Node.js"
echo "npm --version         → Version npm"
echo ""

echo "🐛 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Port déjà utilisé    → Tuer process : kill <PID>"
echo "Module manquant      → npm install"
echo "Cache problème       → npm cache clean --force"
echo "CSV manquant         → Créer src/data/Resume.csv"
echo "API ne répond        → Vérifier npm run server"
echo ""

echo "🚀 DÉPLOIEMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "HEROKU :"
echo "  heroku login"
echo "  heroku create app-name"
echo "  git push heroku main"
echo "  heroku logs --tail"
echo ""
echo "VERCEL (Frontend seul) :"
echo "  npm run build"
echo "  Puis upload build/ sur Vercel"
echo ""

echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "README.md            → Documentation principale"
echo "QUICKSTART.md        → Guide démarrage 5 min"
echo "DEPLOYMENT.md        → Guide déploiement"
echo "TROUBLESHOOTING.md   → Dépannage"
echo "ARCHITECTURE.md      → Architecture du projet"
echo ""

echo "==============================================="
echo "✅ Tapez 'npm run dev' pour démarrer !"
echo "==============================================="
